server:
    port: 2222
    servlet:
        contextPath: /api
spring:
    thymeleaf:
        prefix: classpath:\templates\
        suffix: .html
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sweetrooms?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Africa/Tunis&useLegacyDatetimeCode=false
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: 967158687506915
                        client-secret: 803559ca22a3f6b74d5269cecf740dfc
                        scope:
                            - email
                            - public_profile
                    google:
                        client-id: 1028453501990-qdena8pchvfk54rc5fdh1oi6e9j9v7tp.apps.googleusercontent.com
                        client-secret: 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
    servlet:      
        multipart:
            max-file-size: 2000MB 
    mail:
        host:  smtp.gmail.com
        port: 587
        username: sweetroomapp@gmail.com
        password: Azerty1230
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 25000
                    timeout: 25000
                    writetimeout: 25000
                    starttls:
                        enabled: true
            app_name: SWEET ROOM


springdoc:
    api-docs:
        path: /openapi/v3/api-docs
    packagesToScan: org.sweetrooms.rest
    pathsToMatch: /**
    swagger-ui:
        path: /openapi/swagger-ui.html
sweetrooms:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: sweetRoomsSecretKey
        name: SWEET ROOM
        base-url: http://localhost:4200/
file:
  upload-dir: /root/sweet-room/files
